In [1]:
using Revise
push!(LOAD_PATH, "../src") 
using DataFrames
using CovidDepressionAnalysis
using CSV


In [2]:
# Load Data
data = CSV.read("output/IP_weighted_sources/w12.csv", DataFrame)

LoadError: ArgumentError: "output/IP_weighted_sources/w12.csv" is not a valid file or doesn't exist

In [3]:
# Load Data
data = CSV.read("../data/data_all_impute.csv", DataFrame)

18493×793 DataFrame
   Row │ Column1  PROLIFIC_PID              wave   Fear_COVID_raw  Disgust_COV ⋯
       │ Int64    String31                  Int64  Int64           Int64       ⋯
───────┼────────────────────────────────────────────────────────────────────────
     1 │       0  5df82e8739bcde5dd044f741      1               8              ⋯
     2 │       1  5df82e8739bcde5dd044f741      2               7
     3 │       2  5df82e8739bcde5dd044f741      3              13
     4 │       3  5c7e91c1973c990016ea72b0      1              24
     5 │       4  5c7e91c1973c990016ea72b0      2              25              ⋯
     6 │       5  5c7e91c1973c990016ea72b0      3              23
     7 │       6  5c7e91c1973c990016ea72b0      4              21
     8 │       7  5c7e91c1973c990016ea72b0      5              20
     9 │       8  5c7e91c1973c990016ea72b0      6              21              ⋯
    10 │       9  5c7e91c1973c990016ea72b0      7              21
    11 │      10  5c7e91c1973c990016ea72b0      8              19
   ⋮   │    ⋮                ⋮                ⋮          ⋮                 ⋮   ⋱
 18484 │   18483  58cefdb030c4cf0001ceb3ac      7              16
 18485 │   18484  58cefdb030c4cf0001ceb3ac      8              14              ⋯
 18486 │   18485  58cefdb030c4cf0001ceb3ac      9               9
 18487 │   18486  58cefdb030c4cf0001ceb3ac     10               8
 18488 │   18487  58cefdb030c4cf0001ceb3ac     11              15
 18489 │   18488  58cefdb030c4cf0001ceb3ac     12              16              ⋯
 18490 │   18489  58cefdb030c4cf0001ceb3ac     13              17
 18491 │   18490  58cefdb030c4cf0001ceb3ac     14              15
 18492 │   18491  58cefdb030c4cf0001ceb3ac     15              16
 18493 │   18492  58cefdb030c4cf0001ceb3ac     16              16              ⋯
                                              789 columns and 18472 rows omitted

In [19]:
# Process Meta data
# Set view columns
ENV["COLUMNS"] = 200
# Variables selected
selected_variables = [DEMOGRAPHICS; PSYCHOLOGICAL; EXTERNAL; QUALITY]

20-element Vector{String}:
 "PROLIFIC_PID"
 "Sex"
 "Education"
 "Income_HH"
 "DemM7_KNN"
 "BDI_total_raw"
 "PSS_Total"
 "STAI_State_raw"
 "Fear_COVID_raw_KNN"
 "NIH_TB_Emot_Support_raw_total_KNN"
 "NIH_TB_Loneliness_raw_total_KNN"
 "RW1_8"
 "slope_new_cases"
 "slope_new_deaths"
 "GatheringStrictness_KNN"
 "Mandatory_business_closure"
 "Mandatory_PPE_masks"
 "more_than_1_attQ_failed"
 "string_outlier_core"
 "response_consistency"

In [20]:
w1 = extract_wave(data, 1, selected_variables)
w6 = extract_wave(data, 6, selected_variables)

1797×20 DataFrame
  Row │ PROLIFIC_PID              Sex      Education  Income_HH  DemM7_KNN  BDI_total_raw  PSS_Total  STAI_State_raw  Fear_COVID_raw_KNN  NIH_TB_Emot_Support_raw_total_KNN  NIH_TB_Loneliness_raw_tot ⋯
      │ String31                  Float64  Float64    Float64    Float64    Int64?         Int64?     Int64           Float64             Float64                            Float64                   ⋯
──────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    1 │ 5df82e8739bcde5dd044f741      1.0        3.0        1.0        4.0        missing    missing              42                 8.0                               16.0                            ⋯
    2 │ 5c7e91c1973c990016ea72b0      2.0        5.0        3.0        1.0        missing    missing              69                24.0                               30.0
    3 │ 5e67052c757e6149c38ce468      1.0        1.0        1.0        4.0        missing    missing              57                18.0                               14.0
    4 │ 5d89106d1719af0001ee23e5      2.0        2.0        1.0        6.0        missing    missing              27                 8.0                               40.0
    5 │ 5d6394518df2870001a74b42      2.0        2.0        1.0        1.0        missing    missing              42                23.0                               40.0                            ⋯
    6 │ 5bdd368719b9ba000157fb12      2.0        3.0        4.0        4.0        missing    missing              29                10.0                               40.0
    7 │ 5b68d45687af3100015849a9      2.0        9.0        4.0        1.0        missing    missing              24                11.0                               40.0
    8 │ 5a8ce265000dab00018ce084      2.0        4.0        6.0        3.0        missing    missing              37                 6.0                               34.0
    9 │ 5c72efa770d5a200018028f1      1.0        5.0        2.0        3.0        missing    missing              27                 9.0                               39.0                            ⋯
   10 │ 5d378df21acda30001e7191e      1.0        3.0        2.0        5.0        missing    missing              44                18.0                               10.0
   11 │ 5aea962d0ef2f20001858c9c      1.0        2.0        1.0        2.0        missing    missing              59                17.0                               17.0
  ⋮   │            ⋮                 ⋮         ⋮          ⋮          ⋮            ⋮            ⋮            ⋮                 ⋮                           ⋮                                 ⋮          ⋱
 1788 │ 5de59f97e448c65315ec4a37      2.0        5.0        1.0        1.0        missing    missing              47                16.0                               28.0
 1789 │ 5da926115c6987001535a2da      1.0        5.0        4.0        6.0        missing    missing              27                 2.0                               31.0                            ⋯
 1790 │ 5c054e8a553fb800011917d7      1.0        3.0        1.0        3.0        missing    missing              38                 5.0                               14.0
 1791 │ 5cad4750f4115800176d506e      2.0        4.0        3.0        3.0        missing    missing              49                15.0                               24.0
 1792 │ 5be8846293ca1f00014db03c      2.0        5.0        3.0        5.0        missing    missing              34                13.0                               30.0
 1793 │ 5dbd1569f8223b28d73ed6ae      2.0        3.0        1.0        2.0        missing    missing              32                11.0                               32.0                            ⋯
 1794 │ 5e217a34e8ff3a469b5dfebc      2.0        3.0        5.0        4.0        missing    missing         

In [90]:
data[data[!, "wave"].==1,["PROLIFIC_PID", "wave"]]

1797×2 DataFrame
  Row │ PROLIFIC_PID              wave  
      │ String31                  Int64 
──────┼─────────────────────────────────
    1 │ 5df82e8739bcde5dd044f741      1
    2 │ 5c7e91c1973c990016ea72b0      1
    3 │ 5e67052c757e6149c38ce468      1
    4 │ 5d89106d1719af0001ee23e5      1
    5 │ 5d6394518df2870001a74b42      1
    6 │ 5bdd368719b9ba000157fb12      1
    7 │ 5b68d45687af3100015849a9      1
    8 │ 5a8ce265000dab00018ce084      1
    9 │ 5c72efa770d5a200018028f1      1
   10 │ 5d378df21acda30001e7191e      1
   11 │ 5aea962d0ef2f20001858c9c      1
  ⋮   │            ⋮                ⋮
 1788 │ 5de59f97e448c65315ec4a37      1
 1789 │ 5da926115c6987001535a2da      1
 1790 │ 5c054e8a553fb800011917d7      1
 1791 │ 5cad4750f4115800176d506e      1
 1792 │ 5be8846293ca1f00014db03c      1
 1793 │ 5dbd1569f8223b28d73ed6ae      1
 1794 │ 5e217a34e8ff3a469b5dfebc      1
 1795 │ 5d63867550d0dd0017805976      1
 1796 │ 5e6155e6f169c0046b6d6518      1
 1797 │ 58cefdb030c4cf0001ceb3ac      1
                       1776 rows omitted

In [6]:
ec = eachcol(data)
ec["PROLIFIC_PID"]

18493-element Vector{String31}:
 "5df82e8739bcde5dd044f741"
 "5df82e8739bcde5dd044f741"
 "5df82e8739bcde5dd044f741"
 "5c7e91c1973c990016ea72b0"
 "5c7e91c1973c990016ea72b0"
 "5c7e91c1973c990016ea72b0"
 "5c7e91c1973c990016ea72b0"
 "5c7e91c1973c990016ea72b0"
 "5c7e91c1973c990016ea72b0"
 "5c7e91c1973c990016ea72b0"
 "5c7e91c1973c990016ea72b0"
 "5c7e91c1973c990016ea72b0"
 "5c7e91c1973c990016ea72b0"
 ⋮
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"
 "58cefdb030c4cf0001ceb3ac"

In [8]:
data[1, "PROLIFIC_PID"]

"5df82e8739bcde5dd044f741"

In [21]:
ENV["COLUMNS"] = 200
ismissing.(data[:,r"BDI"])

18493×23 DataFrame
   Row │ BDI_total_raw  BDI1   BDI2   BDI3   BDI4   BDI5   BDI6   BDI7   BDI8   BDI9   BDI10  BDI11  BDI12  BDI13  BDI14  BDI15  BDI16  BDI17  BDI18  BDI19  BDI20  BDI21  BDI_total_raw_KNN 
       │ Bool           Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool   Bool              
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     1 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
     2 │         false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false              false
     3 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
     4 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
     5 │         false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false              false
     6 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
     7 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
     8 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
     9 │         false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false              false
    10 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
    11 │         false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false              false
   ⋮   │       ⋮          ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮            ⋮
 18484 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
 18485 │         false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false              false
 18486 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
 18487 │         false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false              false
 18488 │          true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true   true              false
 18489 │         false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false  false              false
 18490 │         

In [24]:
filter(r -> r.wave == 6, data, view=true)

1178×793 SubDataFrame
  Row │ Column1  PROLIFIC_PID              wave   Fear_COVID_raw  Disgust_COVID_raw  DISG1.1_20  DISG1.1_22  DISG1.2_15  DISG1.2_17  DISG1.2_18  DISG1.2_19  DISG1.2_20  DISG1.2_21  DISG1.2_22  Fear2 ⋯
      │ Int64    String31                  Int64  Int64           Int64              Float64     Float64     Float64     Float64     Float64     Float64     Float64     Float64     Float64     Float ⋯
──────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    1 │       8  5c7e91c1973c990016ea72b0      6              21                 29         5.0         5.0         3.0         5.0         5.0         5.0         3.0         2.0         5.0      4 ⋯
    2 │      24  5e67052c757e6149c38ce468      6              14                 17         5.0         5.0         2.0         2.0         2.0         4.0         1.0         1.0         4.0      3
    3 │      33  5d89106d1719af0001ee23e5      6               0                 12         4.0         1.0         1.0         1.0         3.0         4.0         1.0         1.0         5.0      1
    4 │      49  5d6394518df2870001a74b42      6              17                 28         5.0         5.0         5.0         5.0         1.0         5.0         3.0         3.0         5.0      5
    5 │      65  5bdd368719b9ba000157fb12      6              12                 16         5.0         1.0         1.0         1.0         5.0         5.0         1.0         1.0         5.0      1 ⋯
    6 │      82  5a8ce265000dab00018ce084      6               1                  7         1.0         2.0         1.0         1.0         3.0         3.0         1.0         1.0         3.0      1
    7 │      98  5c72efa770d5a200018028f1      6              13                 20         3.0         3.0         4.0         4.0         2.0         5.0         1.0         3.0         4.0      4
    8 │     115  5aea962d0ef2f20001858c9c      6              11                 17         1.0         5.0         2.0         3.0         2.0         5.0         1.0         2.0         5.0      1
    9 │     130  5e4b793f03c92a08a6d28e3f      6               5                  9         3.0         3.0         2.0         2.0         2.0         2.0         1.0         1.0         2.0      1 ⋯
   10 │     139  5cbc071f2edc3b00018ab097      6              17                 18         2.0         1.0         5.0         4.0         3.0         4.0         1.0         2.0         5.0      4
   11 │     155  5c1b06d9a329230001ecc39c      6               9                 11         1.0         2.0         2.0         4.0         2.0         4.0         1.0         2.0         2.0      2
  ⋮   │    ⋮                ⋮                ⋮          ⋮                 ⋮              ⋮           ⋮           ⋮           ⋮           ⋮           ⋮           ⋮           ⋮           ⋮          ⋮  ⋱
 1169 │   18322  5d94794a521f890016f93604      6              18                 24         4.0         4.0         5.0         3.0         5.0         5.0         1.0         1.0         5.0      5
 1170 │   18353  5de59f97e448c65315ec4a37      6               5                 12         1.0         4.0         2.0         2.0         2.0         3.0         2.0         3.0         2.0      1 ⋯
 1171 │   18381  5c054e8a553fb800011917d7      6               9                 16         3.0         4.0         2.0         3.0         2.0         4.0         2.0         2.0         3.0      2
 1172 │   18397  5cad4750f4115800176d506e      6              14                 23         2.0         5.0         3.0         2.0         4.0         5.0         3.0         3.0         5.0      2
 1173 │   18413  5be8846293ca1f00014db03c      6              11                 15         2.0         2.0         2.0         4.0         2.0         5.0         1.0         1.0  

In [26]:
test = AsTable(data)

AsTable(18493×793 DataFrame
   Row │ Column1  PROLIFIC_PID              wave   Fear_COVID_raw  Disgust_COVID_raw  DISG1.1_20  DISG1.1_22  DISG1.2_15  DISG1.2_17  DISG1.2_18  DISG1.2_19  DISG1.2_20  DISG1.2_21  DISG1.2_22  Fear ⋯
       │ Int64    String31                  Int64  Int64           Int64              Float64     Float64     Float64     Float64     Float64     Float64     Float64     Float64     Float64     Floa ⋯
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     1 │       0  5df82e8739bcde5dd044f741      1               8                 11         1.0         1.0         1.0         2.0         5.0         3.0         1.0         1.0         5.0       ⋯
     2 │       1  5df82e8739bcde5dd044f741      2               7                 12         1.0         1.0         1.0         1.0         5.0         5.0         1.0

In [33]:
df = DataFrame(x1=[1, 2], x2=[3, 4], y=[5, 6])

2×3 DataFrame
 Row │ x1     x2     y     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      3      5
   2 │     2      4      6

In [34]:
select(df, AsTable(:) => ByRow(extrema) => [:lo, :hi])

2×2 DataFrame
 Row │ lo     hi    
     │ Int64  Int64 
─────┼──────────────
   1 │     1      5
   2 │     2      6

In [42]:
select(df, names(df) .=> (x -> x.^2) .=> [:a, :b, :c])

2×3 DataFrame
 Row │ a      b      c     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      9     25
   2 │     4     16     36

In [63]:
transform(df, AsTable(:) .=> ByRow.([sum, x -> sum(x)]) .=> [:a, :b])

2×5 DataFrame
 Row │ x1     x2     y      a      b     
     │ Int64  Int64  Int64  Int64  Int64 
─────┼───────────────────────────────────
   1 │     1      3      5      9      9
   2 │     2      4      6     12     12

In [64]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [65]:
b = 1

1

In [68]:
b .+ a

3-element Vector{Int64}:
 2
 3
 4

In [69]:
c = [5,6,7]

3-element Vector{Int64}:
 5
 6
 7

In [72]:
d = zeros(3,3)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [75]:
e = c .+ d

3×3 Matrix{Float64}:
 5.0  5.0  5.0
 6.0  6.0  6.0
 7.0  7.0  7.0

In [84]:
byrow

3×3 Matrix{Float64}:
 2.23607  2.23607  2.23607
 2.44949  2.44949  2.44949
 2.64575  2.64575  2.64575